### ISSUE TITLE
Restructuring for flexibility

### ISSUE THREAD

**Issue by zrthxn** [sleibrock/mathy#1]
I'd like to try to help with the following todos that you've listed in the readme.
- Differentiation of Complex-valued (basic) functions
- Partial derivatives
- Basic Integration rules

I do have an engineering background and I know the math, since that would be a prerequisite. 
Do let me know if I should start working.

**Comment by sleibrock** [comment]
Hiya! Sorry for the delayed response.

Currently I am working on mapping hyperbolic trig functions to their derivatives as with a library of this kind there is a lot of ground to cover. I have not started work on integration properly as that is a large field by itself ([see xkcd's comic](https://xkcd.com/2117/)), but if there's anything you want to experiment with or improvements I can make, I am open to any kind of pull request for discussion.

Let me know if there's anything you need help with, I don't have any good tutorial programs committed just yet but that is something I am trying to change.

**Comment by zrthxn** [comment]
Hey! That's okay. 

So I've tried a few things here and there. Nothing major yet. I wanted to understand the structure of the library before making too many changes.
If you can give me a short overview of the structure planned for this, that'll be really helpful. I know it might be a lot to explain but just a quick overview will do.

**Comment by sleibrock** [comment]
Happy to help!

For right now, I'm splitting up code into different Rust folders/modules for simplicity sake to make it easier to access components that one might need. At the core of everything, there are two Rust enums used: `Number` and `Expr`. `Number` is what holds Real and Complex values (and can also hold a `NaN` value) while the `Expr` represents an expression tree. `Expr` contains all variants to represent fundamental math operations both unary like negation `Neg`, or binary ops like addition and subtraction (`Add` and `Sub`). If it's unary it contains a boxed reference to another `Expr`, and if it's binary it contains two.

I've split up the modules to try to be logically isolated so that it's easier to navigate and add code to. Number is separate from Expr, but the Expr module will require the Number module, and I separated the Calculus module from the Analysis module since those could be separate for certain reasons (maybe later on certain numerical methods might not inherently require calc or be tied to calc). However this is all up for discussion as I'm new to making a Rust library.

I will try to add some more comments to some of the source files later on today so hopefully that will provide more insight to some weirder places, but it is a lot of pattern matching in most files to match across every variant of `Expr` trees.

**Comment by zrthxn** [comment]
Alright that's really helpful.
I'm considering adding a *Matrix *module for matrix/vector algebra and math.

Is it not more logical to split the existing code into operations and
entities? The entities will be the Number and Expr (maybe Matrix and Vector too
later)  and the operations will be
add/sub/mul/div/exp/mod/differentiate/integrate/transforms etc and they'll
change behaviour (override) based on the operands.

**Comment by sleibrock** [comment]
I was thinking of splitting up the logic somehow, so that the Number source wouldn't have to hold so many math definitions itself. Right now I do a lot of pattern match unwrapping just applying singular operations so I would like a better way of applying operations without repeating so much code. If there is a better approach, I would love to hear more about what could be done so I'm not repeating myself too much when writing tree traversals. A lot of this code is imported from a smaller Haskell program I wrote so I'm always looking for better Rusty ways of doing things.

Matrix and Vectors are also containers I have wanted to add as well, but have yet to get to personally, so help there would be great!

**Comment by zrthxn** [comment]
Alright I'll get back to you with some commits!

**Comment by zrthxn** [comment]
>  Right now I do a lot of pattern match unwrapping just applying singular operations so I would like a better way of applying operations without repeating so much code. 

So I've made a few changes and I'm using `traits` to let every type of `Number` have its own implementation of the logic for a particular function. It's sort of like overriding functions with Inheritance (like in C++ or Java).

**Right now I've only done `Number`.  If you feel this is appropriate, I'll start integrating this approach to the `expr` and `calc` modules as well.**

[Changes to the `Number` type](https://github.com/zrthxn/mathy/blob/7cd786871189701ce86fb35cf1f5794d155f8fee/src/number/number.rs)

[Implementing traits defined in number.rs for `Complex`](https://github.com/zrthxn/mathy/commit/ba704a92d3bff9e62facebc69a14cbbc61bd1b54)

**Comment by sleibrock** [comment]
Hey! Little late to the party here but I will start looking over it and playing around soon.So far it looks great! Will let you know if there's anything I need changed!

**Comment by sleibrock** [comment]
I did some review of the code and overall I'm uncertain if I have much need for traits as it currently stands. My main concern is that by splitting the Number enumeration into separate structs, we lose the ability to write simple expression trees without much advantage. With the current Number enum, we're able to represent all three possibilities of either Real, Complex or NaN in a single data-type. If we wanted to keep the same structure for Expressions, we would need to bundle these new structs into some kind of union enumeration type to represent all possibilities of numbers, or write new variants to represent these structs.

Currently our expression tree is this:
```rust
pub enum Expr {
     Const(Number),
     Var(char),
     ...
}
```
If we wanted to create structs for both Real and Complex, we do either:
```rust
pub enum Expr {
    ConstR(Real),
    ConstC(Complex),
    ....
}
```
Or we union it in another enumeration (which is kind of going in circles)
```rust
pub enum NewNumber {
    Real(Real), Complex(Complex),
}
pub enum Expr {
    Const(NewNumber),
    ....
}
```
For the other traits, I can't say if they are as needed. Traits are good when we have lots of types working together and we need Rust to enforce strictness to make sure these user structs have certain methods bound to them in signatures. But if our Number implementation matches across all variants of the Number enum, then traits doesn't give us anything we don't already have - our Number class is only ever going to interact with other Numbers after all, not necessarily foreign data types.

**Comment by zrthxn** [comment]
I'm not suggesting that the Number enum be removed completely. I think the different types of numbers should be their own structs and the can all be encapsulated in one Number class. This makes sense to me since it gives you the simplicity of the current expression tree and **removes all the pattern matching** by using traits to implement the actual functionality.

The operations that are shared (eg: Print, Add, Sub, Trig etc) by multiple entities (eg: Real, Complex, Expr etc) can be defined by a trait. It will define which operations are possible. So as you implement a new entity (eg: Matrix) you can choose which traits to implement for it. And every "class" of entities, like numbers, can be encapsulated by an enum, like Number, which expresses which types of numbers are available. 
This is just giving every enumeration in the current Number enum its own space. That seems logical to me.

I think making a union is doable since the outside modules need only interact with the `Number` enum while you can keep adding new types of numbers/entities later on.
```rust
pub enum Number {
  Real(Real), Complex(Complex), 
  Matrix(Matrix), Vector(Vector), 
  ...
  NaN
}

pub enum Expr {
  Const(Number)
}
```
I don't see this as going in circles though. With the existing setup you'd have to change every function in the entire Number implementation (and add to the pattern matching) to accommodate a new type of number and/or operation.

**Still, if you don't think this will be beneficial I'll abandon this line of enquiry and work on something else.**

**Comment by sleibrock** [comment]
I'm gonna try to address the critical points which I think we can work on together.

> I think the different types of numbers should be their own structs and the can all be encapsulated in one Number class. This makes sense to me since it gives you the simplicity of the current expression tree and removes all the pattern matching by using traits to implement the actual functionality.

By your suggested code, putting each variant of number into it's own unique struct gives each value a named field by which we can address it. By using traits, we can define the interactions between them. Previously our Add trait looks like this:
```rust
impl Add for Number {
    type Output = Number;
    fn add(&self, other: Number) -> Number {
        match (self, other) {        
            (Real(x), Real(y)) => Real(x + y),
            .... 
            _ => NaN,
    }
}
```
But by your sample code in your Complex struct implementation, it would become more messy because you are then also defining every interaction possible, then deferring the top-level trait operation to use sub-level trait operations. Which hasn't saved us much code, just delegated it elsewhere and added more implement blocks.
```rust
impl Add for Real {
    pub fn add(self, other: Real) -> Real { ... }
}
impl Add<Complex> for Real {
    pub fn add(self, other: Complex) -> Complex { ... }
}
impl Add for Complex {
    pub fn add(self, other: Complex) -> Complex { ... }
}
impl Add<Real> for Complex {
    pub fn add(self, other: Real) -> Complex { ... }
}
pub enum Number { Real(Real), Complex(Complex), NaN, }
impl Add for Number {
    pub fn add(self, other: Number) -> Number {
        match (self, other) {
            (NaN, _) => NaN,
            (_, NaN) => NaN,
            (a, b) => a + b,
        }
    }
}
```
And at the last part, we're still checking for NaN with pattern matching. I'm probably in the wrong here about everything, but it didn't seem like we saved ourselves a whole lot of code going this route. We just put it into more weird places making it harder to get to.

The other traits also don't make much sense to me like Logarithm or Trigonometry, because those are defined across all our numbers so far. Why do those have to be lifted into traits and separated from our current Number implementation? But this part leads into the next point I want to address:

> 2.  So as you implement a new entity (eg: Matrix) you can choose which traits to implement for it.

Based on the code here:
```rust
pub enum Number {
  Real(Real), Complex(Complex), 
  Matrix(Matrix), Vector(Vector), 
  ...
  NaN
}
```
I'm uncertain if I want Matrix or Vector to be considered numbers at all. They aren't really numbers, they're things that contain numbers, not so much numbers themselves. Matrix and Vectors will have to have their own logic separate from raw numbers because their shape matters so much when calculating it. It wouldn't make sense to have to treat them on the same level of things like Real/Complex, because they aren't even remotely the same. Using all that code from earlier before, you'd have to define every interaction possible, so it'd end up looking a whole lot like this:
```rust
impl Add<Matrix> for Real { ... }
impl Add<Vector> for Real { ... }
impl Add<Complex> for Real { ... }
impl Add for Real { ... }
...
```
The underlying issue I have is that eventually I want Matrix and Vector to store Expressions, since there is a branch of calculus for both those types. I do want to add the arithmetic overload operations to support both Vector and Matrix properly, such that expressions like `let a = m*x + b` will work for Matrix transforms and such, but I think that the Number enum should probably be left alone. This is definitely some uncharted territory for me to explore so I just want to do things right to make it easier for anyone who comes here. I think my next goal will be to start defining the Vector class of operations.

As an aside, a lot of this code comes from a [Haskell program](https://github.com/sleibrock/haskell-notes/blob/master/programs/symbolic_calculus.lhs) I wrote a long time ago, and translating it into Rust has been a passion of mine. The idea of using the Rust enumeration feature comes from me using sum-types in Haskell.

**Comment by zrthxn** [comment]
Alright I see. Traits would only replace the pattern matching with a few more lines and still need to have every possible combination in the implementation. Let's move on from this then. 

I think if you could assign a task based on what you're working on now, that'll be a better way to collaborate. 
What do you think?

**Comment by sleibrock** [comment]
I think defining Vectors would be a great contribution and we could work on
laying the foundation for both vector calculus and linear algebra. I'm
undecided on how to define it as best as possible, since it can be done in
fixed-sized formats like with an enumeration type, or an N-sized type using
a struct combined with a containing std::vec storage. I would be okay if it
was restricted to just 2/3/4 dimensions of vectors, but would love to see
another person's input on it.
